DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CATEGORY values ('Lazer');
INSERT INTO CATEGORY values ('Alimentação');
INSERT INTO CATEGORY values ('Supermecado');
INSERT INTO CATEGORY values ('Farmácia');
INSERT INTO CATEGORY values ('Outros');